site_name: IBM Hybrid Cloud Enablement
theme:
  name: material
docs_dir: docs-and-tools
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
