site_name: IBM Hybrid Cloud Enablement
theme:
  name: material
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.instant
      - navigation.indexes
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - toc.integrate
docs_dir: docs-and-tools
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
#   - meta
  - md_in_html
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
#   - pymdownx.snippets:
#       base_path: docs-mk/snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
