# Add mycryptokey to apiconnect domain
spec:
  gateway:
    additionalDomainConfig:
    - name: "apiconnect"
      certs:
      - certType: "usrcerts"
        secret: "mycryptokey"
      dpApp:
        config:
        - "111-apiconnect-mycryptokey-cfg"
